[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Cllvm-args=-fp-contract=fast",
]
[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-Cllvm-args=-fp-contract=fast",
]
[target.aarch64-apple-darwin]
rustflags = [
    "-Cllvm-args=-fp-contract=fast",
]